
name: capstoneproject_mobileapp
description: A health app with profile management.

publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  provider: ^6.0.3

  firebase_core: ^2.32.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_database: ^10.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/profile_pic.jpg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-ExtraBold.ttf
          weight: 800


